### ISSUE TITLE
[Feature] Allow rebinding of config and monitoring keys.

### ISSUE THREAD

**Issue by pikasalt** [RogoShum/BruteForceRenderingCulling#1]
The R and X keys are keys common keys used in modpacks, and currently it seems as if you cannot rebind these in the forge 1.20.1 version.

**Comment by RogoShum** [comment]
I haven't done keybinding function on 1.20.1 forge, which will be add in the next update

**Comment by RogoShum** [comment]
The issue has been fixed in version 0.4.7.
