### ISSUE TITLE
Incompatible with oculus 1.7.0

### ISSUE THREAD

**Issue by kakashi1464** [RogoShum/BruteForceRenderingCulling#11]
Related to https://github.com/RogoShum/BruteForceRenderingCulling/issues/10

[debug.log](https://github.com/RogoShum/BruteForceRenderingCulling/files/15214420/debug.log)
[crash-2024-05-06_01.21.58-client.txt](https://github.com/RogoShum/BruteForceRenderingCulling/files/15214425/crash-2024-05-06_01.21.58-client.txt)
[latest.log](https://github.com/RogoShum/BruteForceRenderingCulling/files/15214441/latest.log)

**Comment by RogoShum** [comment]
In mod version 0.5.9, oculus 1.7.0 is already supported.
