### ISSUE TITLE
DH + Shaders

### ISSUE THREAD

**Issue by chmonyasik** [RogoShum/BruteForceRenderingCulling#13]
Hi! Most likely the problem is the large number of mods in my modpack 🙃, but still would like to tell you about it, I will try to attach as many details as possible, you can ask me to test some elements and let you know the result, if necessary.

Minecraft: 1.20.1
Forge: 47.2.30
Brute force Rendering Culling-forge-1.20.1-0.5.8
Oculus-mc1.20.1-1.6.15aDH
Oculus-flywheel-compat-1.20.1-0.2.4
DistantHorizons-2.0.3-a-dev-1.20.1

(There are already new versions, but they can not be used with flywheel, maybe everything is fixed, and maybe again the problem is not even in these mods, the list of mods should be in crash-report or in logs, but if you need attached - I will attach screenshot of all mods)

[latest.log](https://github.com/RogoShum/BruteForceRenderingCulling/files/15262461/latest.log)
[crash-2024-05-09_14.46.52-client.txt](https://github.com/RogoShum/BruteForceRenderingCulling/files/15262462/crash-2024-05-09_14.46.52-client.txt)
[crash-2024-05-09_15.41.53-client.txt](https://github.com/RogoShum/BruteForceRenderingCulling/files/15262463/crash-2024-05-09_15.41.53-client.txt)

A small description of the problem - if you often turn off / turn on shaders (and sometimes just at a random moment (when culling occurs?)) Minecraft stops and happens everything in the screenshots below, as I understand - it crashed, but not to the end or so, because from the world I left, all the sounds are gone, but window is here.

![Screenshot_6](https://github.com/RogoShum/BruteForceRenderingCulling/assets/94359925/dc70f8cf-486a-4c66-bcd1-ee1aa2068d40)

![Screenshot_3](https://github.com/RogoShum/BruteForceRenderingCulling/assets/94359925/b1191d4d-91ed-419d-acfd-2f367b12d39b)

**Comment by RogoShum** [comment]
In mod version 0.5.9, the crash issue when switching shaders has been fixed. Flywheel compat was updated last week, and I have tested that the latest version of Flywheel compat is compatible with the culling mod and Oculus.

**Comment by chmonyasik** [comment]
> In mod version 0.5.9, the crash issue when switching shaders has been fixed. Flywheel compat was updated last week, and I have tested that the latest version of Flywheel compat is compatible with the culling mod and Oculus.

Thanks! I'll have to test it, if anything I'll post again, by the way, is there any way to cull entity from create, I understand flywheel doesn't let you do that? Is there any way to override it?
![image](https://github.com/RogoShum/BruteForceRenderingCulling/assets/94359925/13373b27-ce06-4d85-92eb-999ded11bb09)

**Comment by RogoShum** [comment]
> > In mod version 0.5.9, the crash issue when switching shaders has been fixed. Flywheel compat was updated last week, and I have tested that the latest version of Flywheel compat is compatible with the culling mod and Oculus.
> 
> Thanks! I'll have to test it, if anything I'll post again, by the way, is there any way to cull entity from create, I understand flywheel doesn't let you do that? Is there any way to override it? ![image](https://private-user-images.githubusercontent.com/94359925/333205492-13373b27-ce06-4d85-92eb-999ded11bb09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzIzMTEsIm5iZiI6MTcxNjQ3MjAxMSwicGF0aCI6Ii85NDM1OTkyNS8zMzMyMDU0OTItMTMzNzNiMjctY2UwNi00ZDg1LTkyZWItOTk5ZGVkMTFiYjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEzNDY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNWEzZmMyYWRjYjBmZjIyYWIxOWI5OWIxNTNmNDRmODMzOGVjY2JhY2Y0N2UzMjZiMDhmZmZiMWZhMzlmZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w9BWsZG7ek5epfILMGAvQfcz2yoKRcX-sq7QDz0i3WM)

I briefly reviewed the flywheel code and didn't find any conflicting parts. However, the purpose of flywheel itself is to optimize entity rendering, and the technology used by flywheel theoretically provides similar optimization to direct entity culling. If flywheel's entity optimization functions properly, there should be no significant impact. I'll check what's causing the issue in the next few days if I have time. If it's confirmed to be a serious problem, I can try to fix it.

**Comment by chmonyasik** [comment]
Thanks! Unfortunately I can not give much information, maybe in the new versions of create it all fixed, or maybe it does not affect fps, but as for me, it is strange that if you fly away even further than chunks distance, block entities still remain and moreover spin (non static models?), + flywheel also affect chests. Anyway, good luck and hope you are doing well.

https://github.com/Creators-of-Create/Create/issues/6508

**Comment by RogoShum** [comment]
> Thanks! Unfortunately I can not give much information, maybe in the new versions of create it all fixed, or maybe it does not affect fps, but as for me, it is strange that if you fly away even further than chunks distance, block entities still remain and moreover spin (non static models?), + flywheel also affect chests. Anyway, good luck and hope you are doing well.
> 
> [Creators-of-Create/Create#6508](https://github.com/Creators-of-Create/Create/issues/6508)

This seems to be an issue with Create. My functionality is to cull occluded entities, but the entities in the screenshot are not occluded. Ideally, if these entities from Create are occluded, they should be culled correctly.
