### ISSUE TITLE
Certain angles don't display entities even if in view

### ISSUE THREAD

**Issue by R00tB33rMan** [RogoShum/BruteForceRenderingCulling#14]
![image](https://github.com/RogoShum/BruteForceRenderingCulling/assets/36140389/c9dafbde-afbd-4bfa-8a07-e44c6266e490) (Different angle and not working)

![image](https://github.com/RogoShum/BruteForceRenderingCulling/assets/36140389/f5ebbf5d-989e-4a18-a3ec-ea75a32348a3)
(Working angle)

This applies to shulkers and other block entities as well; however, I thought it'd be worth mentioning.

**Comment by RogoShum** [comment]
In my tests, the latest version 0.5.9 doesn't seem to have this issue. There was a bug in version 0.5.7, but it has been fixed starting from version 0.5.8. Are you still encountering this bug when using version 0.5.8 or later?
