### ISSUE TITLE
[1.20.1] Mod doesn't make any difference with Embeddium Installed

### ISSUE THREAD

**Issue by wabeb325** [RogoShum/BruteForceRenderingCulling#22]
- Description:
In the last version of Embeddium [0.3.21], when you use the mod, there is no impact on the performance and even it looks like is deactivated, because when you activate the Async function, there is no impact, even with the mod disabled and enable, the same happens with the Entity Culling mod, but with this one is more noticeable.

- How to test it? 
1) Install Embeddium and Brute Force Culling by default
2) Do a Benchmark with and without the mod and you will se no difference.

**Comment by DeshiDesu** [comment]
OP's source: Trust me bro

**Comment by wabeb325** [comment]
Well, **TRY AND SEE**, this was a bug of Embeddium and was already fixed in the 0.3.25, so there's no reason to keep this open.

**Comment by DeshiDesu** [comment]
Fair point, although I think there's a general consensus that issues need to always have evidence to hold credibility. Its just the right thing to do.
