### ISSUE TITLE
Crash With Oculus [1.18.2]

### ISSUE THREAD

**Issue by wabeb325** [RogoShum/BruteForceRenderingCulling#4]
In the latest version of the mod, when entering a world using shaders, the game crashes.

- Minecraft: 1.18.2
- Forge: 40.2.17

Crash Report:
[crash-2024-04-12_13.27.07-client.txt](https://github.com/RogoShum/BruteForceRenderingCulling/files/14961671/crash-2024-04-12_13.27.07-client.txt)

**Comment by RogoShum** [comment]
The issue has been fixed in version 0.4.7. Update for compatibility with Oculus version 1.6.4.
