### ISSUE TITLE
1.20.4 Support for Fabric

### ISSUE THREAD

**Issue by PhantomG27249** [RogoShum/BruteForceRenderingCulling#5]
Would it be possible to support the 1.20.4 fabric?

**Comment by RogoShum** [comment]
Sure! However, it will take some time. Currently, the functionality of the mod is not yet stable enough and will require multiple updates for further improvements. It's not suitable for migrating to minor version numbers, as subsequent updates would become cumbersome. Most lightweight mods for 1.20.1 also support versions 1.20.1-1.20.4. My project version is 1.20.1, and it hasn't been directly tested in a 1.20.4 environment yet. It may actually be compatible with version 1.20.4.

**Comment by RogoShum** [comment]
Support for version 1.20.4 has been added.
