### ISSUE TITLE
Dimension chunk culling blacklist.

### ISSUE THREAD

**Issue by maximogta** [RogoShum/BruteForceRenderingCulling#6]
Could a chunk culling blacklist be added for dimensions?

Because it works well in the overworld, but in the end and nether dimension it culls chunks even in front of me.

Thank you, very cool optimization mod.

**Comment by RogoShum** [comment]
This issue arises from the failure to successfully refresh the cache when switching dimensions and can be resolved by re-entering the map. It will be fixed in the next version.

**Comment by maximogta** [comment]
Thanks

**Comment by DeshiDesu** [comment]
Can confirm the culling breaks when switching dimensions

**Comment by RogoShum** [comment]
This issue has been resolved in the latest version.
