### ISSUE TITLE
Async Rebuild Chunk momentarily unrenders chunks when changing window size

### ISSUE THREAD

**Issue by DeshiDesu** [RogoShum/BruteForceRenderingCulling#7]
Brute force Rendering Culling-forge-1.20.1-0.5.5.jar
embeddium-0.3.14+mc1.20.1.jar
Forge 47.2.30

Returns to normal after a moment of processing from the mod.
Issue does not exist when turning off Async Rebuild Chunk
Images are taken from my modpack but I have also tested from a separate instance with only Brute force and embeddium installed.
![image](https://github.com/RogoShum/BruteForceRenderingCulling/assets/120287925/03584af7-4b93-469f-a63a-499ca3377f8c)
![image](https://github.com/RogoShum/BruteForceRenderingCulling/assets/120287925/1db14cea-2586-4438-9e3f-bbb352bf9ece)

**Comment by RogoShum** [comment]
This issue has been resolved in the latest version.
