### ISSUE TITLE
[BUG] Game crashes while using Architectury 9.2.14 under specific conditions

### ISSUE THREAD

**Issue by Delfite** [RogoShum/BruteForceRenderingCulling#8]
### **Environment**
Minecraft version: ``1.20.1``
Java version: ``17.0.11.9``
Fabric version: ``0.15.10``
Fabric API version: ``0.92.1``
Mod version: ``0.5.5``

### **Issue Description**
Minecraft crashes when performing certain actions that involve rendering specific screen elements. Actions include...
-Hovering over a button on (what I can only assume is) any settings submenu
-Hovering over an item in your inventory
-Hovering over clickable text in the in-game text chat

### **Steps to recreate the issue**
1. Install Fabric 0.15.10 and Fabric API 0.92.1
2. Install Brute Force Culling 0.5.5
3. Install [Architectury 9.2.14](https://modrinth.com/mod/architectury-api/version/9.2.14+fabric)
4. Go to ``Options > Video Settings``
5. Hover over any button while in the video settings
6. The game should crash immediately upon hovering over a button in a submenu

### **Relevant attachments**
[Latest.log](https://gnomebot.dev/paste/397702104204050434/1234921628052226151/1234921627691651194)

### **Notes**
This took hours to debug and document. I am in pain.

**Comment by RogoShum** [comment]
Thank you for your feedback. This issue has been fixed in development and the updated version with the fix will be released shortly.

**Comment by RogoShum** [comment]
The issue has been fixed in version 0.5.8.
